name: SonarCloud Analysis
on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    sonarcloud:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  distribution: 'adopt'
                  java-version: '11'
            - name: Build
              run: |
                  find src -name "*.java" -print > sources.txt
                  javac -cp "lib/*:!lib/mysql/mysql-connector-java-5.1.15-bin.jar" -d build/classes @sources.txt
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
